# Generated by Django 4.1 on 2023-01-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('age', models.IntegerField(default=0, verbose_name='age')),
                ('date_of_arrival', models.DateTimeField(auto_now=True, verbose_name='date_of_arrival')),
                ('weight', models.IntegerField(blank=True, default=0, verbose_name='weight')),
                ('height', models.IntegerField(blank=True, default=0, verbose_name='height')),
                ('special_signs', models.CharField(blank=True, max_length=1000, null=True, verbose_name='special_signs')),
            ],
            options={
                'verbose_name': 'pet',
                'verbose_name_plural': 'pets',
            },
        ),
    ]
